### PR TITLE
Add topic un-/subscribe events

### PR DESCRIPTION
**Pull request by muXxer**
This PR adds new events to also get notified if a subscription is created or removed.

### CODE REVIEW

**Comment by muXxer** [comment]
@mochi-co can you have a look at this? :)
Thank you!

**Comment by mochi-co** [comment]
Thanks for your patience @muXxer! I have merged this into master, however before we release it I am going to change the Client string to use the events.Client type, and also add some tests.

**Comment by mochi-co** [comment]
This has been released as `v1.2.2`. The function signatures for the events have been changed as follows:


##### OnSubscribe
`server.Events.OnSubscribe` is called when a client subscribes to a new topic filter.

```go
server.Events.OnSubscribe = func(filter string, cl events.Client, qos byte) {
    fmt.Printf("<< OnSubscribe client subscribed %s: %s %v\n", cl.ID, filter, qos)
}
```

##### OnUnsubscribe
`server.Events.OnUnsubscribe` is called when a client unsubscribes from a topic filter.

```go
server.Events.OnUnsubscribe = func(filter string, cl events.Client) {
    fmt.Printf("<< OnUnsubscribe client unsubscribed %s: %s\n", cl.ID, filter)
}
```

Thank you for the contribution, @muXxer ! :)

**Comment by muXxer** [comment]
Cool, thanks for merging!

**Pull request merged**
